Alt way for installing cpanm.
The error message suggest that on macos-intel runner, `cpanm` isn't
found in PATH:

    Run cpanm --verbose ./App-perlbrew-*
      cpanm --verbose ./App-perlbrew-*
      shell: /bin/bash -e {0}
    /Users/runner/work/_temp/b0f0e75a-43f7-407a-82f4-e331aba4cfd6.sh: line 1: cpanm: command not found
    Error: Process completed with exit code 127.

Detail: https://github.com/gugod/App-perlbrew/actions/runs/26425656783/job/77788728463

So we'll just put it under the workspace: