Add order for http_user_agent_program
perlbrew install-cpanm or install-patchperl fail,

    ERROR: Failed to retrieve cpanm executable.

because https://raw.github.com/ provides a certificate with SAN (Subject
Alternative Name) attribute but wget <= 1.12 does not support SAN, so prefer
to use curl.